CREATE TABLE all_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,  -- 从 1000 开始自增
    stock_code TEXT NOT NULL,          -- 股票代码
    short_name TEXT NOT NULL,          -- 股票简称
    exchange TEXT,                     -- 交易所
    list_date DATE,                    -- 上市日期
    UNIQUE(stock_code)                 -- 确保股票代码唯一
);

-- 添加表注释
COMMENT ON TABLE all_stocks IS '存储所有股票的基本信息';

-- 添加字段注释
COMMENT ON COLUMN all_stocks.id IS '自增主键，从 1000 开始';
COMMENT ON COLUMN all_stocks.stock_code IS '股票代码';
COMMENT ON COLUMN all_stocks.short_name IS '股票简称';
COMMENT ON COLUMN all_stocks.exchange IS '交易所';
COMMENT ON COLUMN all_stocks.list_date IS '上市日期';