CREATE TABLE ok_finance_kline_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    stock_code TEXT NOT NULL,
    trade_time TIMESTAMP NOT NULL,
    trade_date DATE NOT NULL,
    open FLOAT,
    close FLOAT,
    high FLOAT,
    low FLOAT,
    volume BIGINT,
    amount FLOAT,
    change_pct FLOAT,
    change FLOAT,
    turnover_ratio FLOAT,
    pre_close FLOAT,
    UNIQUE(stock_code, trade_date)
);

-- 添加表注释
COMMENT ON TABLE ok_finance_kline_daily IS '存储所有股票的日K线数据';

-- 添加字段注释
COMMENT ON COLUMN ok_finance_kline_daily.id IS '自增主键，从 1000 开始';
COMMENT ON COLUMN ok_finance_kline_daily.stock_code IS '股票代码';
COMMENT ON COLUMN ok_finance_kline_daily.trade_time IS '交易时间';
COMMENT ON COLUMN ok_finance_kline_daily.trade_date IS '交易日期';
COMMENT ON COLUMN ok_finance_kline_daily.open IS '开盘价';
COMMENT ON COLUMN ok_finance_kline_daily.close IS '收盘价';
COMMENT ON COLUMN ok_finance_kline_daily.high IS '最高价';
COMMENT ON COLUMN ok_finance_kline_daily.low IS '最低价';
COMMENT ON COLUMN ok_finance_kline_daily.volume IS '成交量';
COMMENT ON COLUMN ok_finance_kline_daily.amount IS '成交额';
COMMENT ON COLUMN ok_finance_kline_daily.change_pct IS '涨跌幅百分比';
COMMENT ON COLUMN ok_finance_kline_daily.change IS '涨跌额';
COMMENT ON COLUMN ok_finance_kline_daily.turnover_ratio IS '换手率';
COMMENT ON COLUMN ok_finance_kline_daily.pre_close IS '前收盘价';

-- 添加索引
CREATE INDEX idx_stock_code ON ok_finance_kline_daily (stock_code);
CREATE INDEX idx_trade_date ON ok_finance_kline_daily (trade_date);
CREATE INDEX idx_stock_code_trade_date ON ok_finance_kline_daily (stock_code, trade_date);




CREATE TABLE ok_finance_kline_weekly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    stock_code TEXT NOT NULL,
    trade_time TIMESTAMP NOT NULL,
    trade_date DATE NOT NULL,
    open FLOAT,
    close FLOAT,
    high FLOAT,
    low FLOAT,
    volume BIGINT,
    amount FLOAT,
    change_pct FLOAT,
    change FLOAT,
    turnover_ratio FLOAT,
    pre_close FLOAT,
    UNIQUE(stock_code, trade_date)
);

-- 添加表注释
COMMENT ON TABLE ok_finance_kline_weekly IS '存储所有股票的周K线数据';

-- 添加字段注释
COMMENT ON COLUMN ok_finance_kline_weekly.id IS '自增主键，从 1000 开始';
COMMENT ON COLUMN ok_finance_kline_weekly.stock_code IS '股票代码';
COMMENT ON COLUMN ok_finance_kline_weekly.trade_time IS '交易时间';
COMMENT ON COLUMN ok_finance_kline_weekly.trade_date IS '交易日期';
COMMENT ON COLUMN ok_finance_kline_weekly.open IS '开盘价';
COMMENT ON COLUMN ok_finance_kline_weekly.close IS '收盘价';
COMMENT ON COLUMN ok_finance_kline_weekly.high IS '最高价';
COMMENT ON COLUMN ok_finance_kline_weekly.low IS '最低价';
COMMENT ON COLUMN ok_finance_kline_weekly.volume IS '成交量';
COMMENT ON COLUMN ok_finance_kline_weekly.amount IS '成交额';
COMMENT ON COLUMN ok_finance_kline_weekly.change_pct IS '涨跌幅百分比';
COMMENT ON COLUMN ok_finance_kline_weekly.change IS '涨跌额';
COMMENT ON COLUMN ok_finance_kline_weekly.turnover_ratio IS '换手率';
COMMENT ON COLUMN ok_finance_kline_weekly.pre_close IS '前收盘价';

-- 添加索引
CREATE INDEX idx_stock_code ON ok_finance_kline_weekly (stock_code);
CREATE INDEX idx_trade_date ON ok_finance_kline_weekly (trade_date);
CREATE INDEX idx_stock_code_trade_date ON ok_finance_kline_weekly (stock_code, trade_date);




CREATE TABLE ok_finance_kline_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    stock_code TEXT NOT NULL,
    trade_time TIMESTAMP NOT NULL,
    trade_date DATE NOT NULL,
    open FLOAT,
    close FLOAT,
    high FLOAT,
    low FLOAT,
    volume BIGINT,
    amount FLOAT,
    change_pct FLOAT,
    change FLOAT,
    turnover_ratio FLOAT,
    pre_close FLOAT,
    UNIQUE(stock_code, trade_date)
);

-- 添加表注释
COMMENT ON TABLE ok_finance_kline_monthly IS '存储所有股票的月K线数据';

-- 添加字段注释
COMMENT ON COLUMN ok_finance_kline_monthly.id IS '自增主键，从 1000 开始';
COMMENT ON COLUMN ok_finance_kline_monthly.stock_code IS '股票代码';
COMMENT ON COLUMN ok_finance_kline_monthly.trade_time IS '交易时间';
COMMENT ON COLUMN ok_finance_kline_monthly.trade_date IS '交易日期';
COMMENT ON COLUMN ok_finance_kline_monthly.open IS '开盘价';
COMMENT ON COLUMN ok_finance_kline_monthly.close IS '收盘价';
COMMENT ON COLUMN ok_finance_kline_monthly.high IS '最高价';
COMMENT ON COLUMN ok_finance_kline_monthly.low IS '最低价';
COMMENT ON COLUMN ok_finance_kline_monthly.volume IS '成交量';
COMMENT ON COLUMN ok_finance_kline_monthly.amount IS '成交额';
COMMENT ON COLUMN ok_finance_kline_monthly.change_pct IS '涨跌幅百分比';
COMMENT ON COLUMN ok_finance_kline_monthly.change IS '涨跌额';
COMMENT ON COLUMN ok_finance_kline_monthly.turnover_ratio IS '换手率';
COMMENT ON COLUMN ok_finance_kline_monthly.pre_close IS '前收盘价';

-- 添加索引
CREATE INDEX idx_stock_code ON ok_finance_kline_monthly (stock_code);
CREATE INDEX idx_trade_date ON ok_finance_kline_monthly (trade_date);
CREATE INDEX idx_stock_code_trade_date ON ok_finance_kline_monthly (stock_code, trade_date);