import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
from datetime import datetime
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """
    检查表是否存在
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False




# 查询数据库中是否已存在该股票的数据
def has_stock_data(conn, stock_code):
    """
    查询数据库中是否已存在该股票的数据
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM ok_finance_stock_shares
                WHERE stock_code = %s
            );
        """, (stock_code,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if stock data exists: {e}")
        return False
# 创建股本信息表（如果不存在）并添加注释
def create_stock_shares_table(conn):
    """
    创建股本信息表（如果不存在）并添加注释
    """
    table_name = 'ok_finance_stock_shares'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            # 修改字段类型为 VARCHAR(64)
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code VARCHAR(64) NOT NULL,
                    total_shares NUMERIC(20, 0),
                    limit_shares NUMERIC(20, 0),
                    list_a_shares NUMERIC(20, 0),
                    change_reason VARCHAR(64),
                    change_date VARCHAR(64) NOT NULL,  -- 修改为 VARCHAR
                    UNIQUE(stock_code, change_date)
                );
            """).format(sql.Identifier(table_name)))
            
            # 更新字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码（最大长度64字符）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_reason IS '变更原因（最大长度64字符）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_date IS '变更日期（YYYY-MM-DD格式字符串）';").format(sql.Identifier(table_name)))

            # 索引保持不变
            cur.execute(sql.SQL("CREATE INDEX idx_stock_shares_stock_code ON {} (stock_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_stock_shares_change_date ON {} (change_date);").format(sql.Identifier(table_name)))
            
            conn.commit()
            print(f"Table {table_name} 创建成功（使用VARCHAR类型）")
        else:
            print(f"Table {table_name} 已存在")
    except Exception as e:
        print(f"创建表失败: {e}")

def insert_or_update_stock_shares(conn, stock_code, shares_data):
    """
    插入或更新股本信息（适配VARCHAR类型）
    """
    try:
        # 转换日期格式为字符串
        if 'change_date' in shares_data.columns:
            shares_data['change_date'] = shares_data['change_date'].astype(str)
            
        # 处理数值字段空值
        numeric_cols = ['total_shares', 'limit_shares', 'list_a_shares']
        for col in numeric_cols:
            shares_data[col] = shares_data[col].apply(lambda x: x if pd.notnull(x) else None)

        # 批量插入
        extras.execute_values(
            conn.cursor(),
            """
            INSERT INTO ok_finance_stock_shares (
                stock_code, total_shares, limit_shares, list_a_shares, 
                change_reason, change_date
            )
            VALUES %s
            ON CONFLICT (stock_code, change_date) DO UPDATE
            SET
                total_shares = EXCLUDED.total_shares,
                limit_shares = EXCLUDED.limit_shares,
                list_a_shares = EXCLUDED.list_a_shares,
                change_reason = EXCLUDED.change_reason
            """,
            [
                (
                    stock_code,
                    row['total_shares'],
                    row['limit_shares'],
                    row['list_a_shares'],
                    str(row['change_reason'])[:64],  # 确保不超过64字符
                    str(row['change_date'])[:10]     # 截取前10位 YYYY-MM-DD
                )
                for _, row in shares_data.iterrows()
            ],
            page_size=500
        )
        conn.commit()
        print(f"成功更新 {len(shares_data)} 条股本数据（股票代码：{stock_code}）")
    except Exception as e:
        print(f"数据更新失败: {e}")
        conn.rollback()

# 获取股本信息
def fetch_stock_shares(stock_code, is_history=True):
    try:
        df = adata.stock.info.get_stock_shares(stock_code=stock_code, is_history=is_history)
        print(f"Fetched stock shares data for stock {stock_code} successfully!")
        return df
    except Exception as e:
        print(f"Error fetching stock shares data for stock {stock_code}: {e}")
        return None

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建股本信息表（如果不存在）并添加注释
        create_stock_shares_table(conn)

        # 获取所有股票代码
        # stocks_df = adata.stock.info.all_code()

        # 创建一个包含固定股票代码的 DataFrame 用于测试
        stocks_df = pd.DataFrame({
            'stock_code': ['600001', '600000']  # 示例股票代码
        })
        if stocks_df is None:
            return
        
        # 遍历所有股票代码
        for index, row in stocks_df.iterrows():
            stock_code = row['stock_code']
            
            # 检查数据库中是否已存在该股票的数据
            # if has_stock_data(conn, stock_code):
            #     # 如果存在，则只获取最新数据
            #     shares_data = fetch_stock_shares(stock_code, is_history=False)
            # else:
            #     # 如果不存在，则获取所有历史数据
            #     shares_data = fetch_stock_shares(stock_code, is_history=True)
            if not has_stock_data(conn, stock_code):
                shares_data = fetch_stock_shares(stock_code, is_history=True)
                if shares_data is not None:
                    # 插入或更新股本信息
                    insert_or_update_stock_shares(conn, stock_code, shares_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()