import adata
import psycopg2
import pandas as pd
from psycopg2 import sql

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

def create_finance_core_index_table(conn):
    table_name = 'ok_finance_stock_core_index'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code VARCHAR(20) NOT NULL,
                    short_name VARCHAR(50) NOT NULL,
                    report_date DATE NOT NULL,
                    report_type VARCHAR(20),
                    notice_date DATE,
                    basic_eps DECIMAL(40,6),
                    diluted_eps DECIMAL(40,6),
                    non_gaap_eps DECIMAL(40,6),
                    net_asset_ps DECIMAL(40,6),
                    cap_reserve_ps DECIMAL(40,6),
                    undist_profit_ps DECIMAL(40,6),
                    oper_cf_ps DECIMAL(40,6),
                    total_rev DECIMAL(40,6),
                    gross_profit DECIMAL(40,6),
                    net_profit_attr_sh DECIMAL(40,6),
                    non_gaap_net_profit DECIMAL(40,6),
                    total_rev_yoy_gr DECIMAL(40,6),
                    net_profit_yoy_gr DECIMAL(40,6),
                    non_gaap_net_profit_yoy_gr DECIMAL(40,6),
                    total_rev_qoq_gr DECIMAL(40,6),
                    net_profit_qoq_gr DECIMAL(40,6),
                    non_gaap_net_profit_qoq_gr DECIMAL(40,6),
                    roe_wtd DECIMAL(40,6),
                    roe_non_gaap_wtd DECIMAL(40,6),
                    roa_wtd DECIMAL(40,6),
                    gross_margin DECIMAL(40,6),
                    net_margin DECIMAL(40,6),
                    adv_receipts_to_rev DECIMAL(40,6),
                    net_cf_sales_to_rev DECIMAL(40,6),
                    oper_cf_to_rev DECIMAL(40,6),
                    eff_tax_rate DECIMAL(40,6),
                    curr_ratio DECIMAL(40,6),
                        quick_ratio DECIMAL(40,6),
                    cash_flow_ratio DECIMAL(40,6),
                    asset_liab_ratio DECIMAL(40,6),
                    equity_multiplier DECIMAL(40,6),
                    equity_ratio DECIMAL(40,6),
                    total_asset_turn_days DECIMAL(40,6),
                    inv_turn_days DECIMAL(40,6),
                    acct_recv_turn_days DECIMAL(40,6),
                    total_asset_turn_rate DECIMAL(40,6),
                    inv_turn_rate DECIMAL(40,6),
                    acct_recv_turn_rate DECIMAL(40,6)
                );
            """).format(sql.Identifier(table_name)))

            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票财务核心指标';").format(sql.Identifier(table_name)))
            conn.commit()
            print(f"Table {table_name} created successfully with comments!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

def handle_none(value):
    return None if value is pd.NA or pd.isna(value) else value

def finance_core_index_exists(conn, stock_code):
    table_name = 'ok_finance_stock_core_index'
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            SELECT EXISTS (
                SELECT 1
                FROM {}
                WHERE stock_code = %s
            );
        """).format(sql.Identifier(table_name)), (stock_code,))
        return cur.fetchone()[0]
    except Exception as e:
        print(f"Error checking if finance core index exists for {stock_code}: {e}")
        return False

def insert_finance_core_index(conn, core_index_data):
    table_name = 'ok_finance_stock_core_index'
    try:
        cur = conn.cursor()

        # 替换 nan 为 None
        core_index_data = core_index_data.where(pd.notnull(core_index_data), None)

        for index, row in core_index_data.iterrows():
            stock_code = row['stock_code']
            short_name = row['short_name']
            report_date = handle_none(row['report_date'])
            report_type = handle_none(row.get('report_type'))
            notice_date = handle_none(row.get('notice_date'))
            basic_eps = handle_none(row.get('basic_eps'))
            diluted_eps = handle_none(row.get('diluted_eps'))
            non_gaap_eps = handle_none(row.get('non_gaap_eps'))
            net_asset_ps = handle_none(row.get('net_asset_ps'))
            cap_reserve_ps = handle_none(row.get('cap_reserve_ps'))
            undist_profit_ps = handle_none(row.get('undist_profit_ps'))
            oper_cf_ps = handle_none(row.get('oper_cf_ps'))
            total_rev = handle_none(row.get('total_rev'))
            gross_profit = handle_none(row.get('gross_profit'))
            net_profit_attr_sh = handle_none(row.get('net_profit_attr_sh'))
            non_gaap_net_profit = handle_none(row.get('non_gaap_net_profit'))
            total_rev_yoy_gr = handle_none(row.get('total_rev_yoy_gr'))
            net_profit_yoy_gr = handle_none(row.get('net_profit_yoy_gr'))
            non_gaap_net_profit_yoy_gr = handle_none(row.get('non_gaap_net_profit_yoy_gr'))
            total_rev_qoq_gr = handle_none(row.get('total_rev_qoq_gr'))
            net_profit_qoq_gr = handle_none(row.get('net_profit_qoq_gr'))
            non_gaap_net_profit_qoq_gr = handle_none(row.get('non_gaap_net_profit_qoq_gr'))
            roe_wtd = handle_none(row.get('roe_wtd'))
            roe_non_gaap_wtd = handle_none(row.get('roe_non_gaap_wtd'))
            roa_wtd = handle_none(row.get('roa_wtd'))
            gross_margin = handle_none(row.get('gross_margin'))
            net_margin = handle_none(row.get('net_margin'))
            adv_receipts_to_rev = handle_none(row.get('adv_receipts_to_rev'))
            net_cf_sales_to_rev = handle_none(row.get('net_cf_sales_to_rev'))
            oper_cf_to_rev = handle_none(row.get('oper_cf_to_rev'))
            eff_tax_rate = handle_none(row.get('eff_tax_rate'))
            curr_ratio = handle_none(row.get('curr_ratio'))
            quick_ratio = handle_none(row.get('quick_ratio'))
            cash_flow_ratio = handle_none(row.get('cash_flow_ratio'))
            asset_liab_ratio = handle_none(row.get('asset_liab_ratio'))
            equity_multiplier = handle_none(row.get('equity_multiplier'))
            equity_ratio = handle_none(row.get('equity_ratio'))
            total_asset_turn_days = handle_none(row.get('total_asset_turn_days'))
            inv_turn_days = handle_none(row.get('inv_turn_days'))
            acct_recv_turn_days = handle_none(row.get('acct_recv_turn_days'))
            total_asset_turn_rate = handle_none(row.get('total_asset_turn_rate'))
            inv_turn_rate = handle_none(row.get('inv_turn_rate'))
            acct_recv_turn_rate = handle_none(row.get('acct_recv_turn_rate'))

            values_to_insert = (
                stock_code, short_name, report_date, report_type, notice_date, basic_eps,
                diluted_eps, non_gaap_eps, net_asset_ps, cap_reserve_ps, undist_profit_ps,
                oper_cf_ps, total_rev, gross_profit, net_profit_attr_sh, non_gaap_net_profit,
                total_rev_yoy_gr, net_profit_yoy_gr, non_gaap_net_profit_yoy_gr,
                total_rev_qoq_gr, net_profit_qoq_gr, non_gaap_net_profit_qoq_gr,
                roe_wtd, roe_non_gaap_wtd, roa_wtd, gross_margin, net_margin,
                adv_receipts_to_rev, net_cf_sales_to_rev, oper_cf_to_rev,
                eff_tax_rate, curr_ratio, quick_ratio, cash_flow_ratio,
                asset_liab_ratio, equity_multiplier, equity_ratio,
                total_asset_turn_days, inv_turn_days, acct_recv_turn_days,
                total_asset_turn_rate, inv_turn_rate, acct_recv_turn_rate
            )

            try:
                cur.execute(sql.SQL("""
                    INSERT INTO {} (
                        stock_code, short_name, report_date, report_type, notice_date, basic_eps,
                        diluted_eps, non_gaap_eps, net_asset_ps, cap_reserve_ps, undist_profit_ps,
                        oper_cf_ps, total_rev, gross_profit, net_profit_attr_sh, non_gaap_net_profit,
                        total_rev_yoy_gr, net_profit_yoy_gr, non_gaap_net_profit_yoy_gr,
                        total_rev_qoq_gr, net_profit_qoq_gr, non_gaap_net_profit_qoq_gr,
                        roe_wtd, roe_non_gaap_wtd, roa_wtd, gross_margin, net_margin,
                        adv_receipts_to_rev, net_cf_sales_to_rev, oper_cf_to_rev,
                        eff_tax_rate, curr_ratio, quick_ratio, cash_flow_ratio,
                        asset_liab_ratio, equity_multiplier, equity_ratio,
                        total_asset_turn_days, inv_turn_days, acct_recv_turn_days,
                        total_asset_turn_rate, inv_turn_rate, acct_recv_turn_rate
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s, %s, %s, %s,
                            %s, %s, %s, %s, %s, %s, %s, %s
                )""").format(sql.Identifier(table_name)), values_to_insert)
            except Exception as insert_error:
                print(f"Insert error for stock code {stock_code}: {insert_error}")

        conn.commit()
        print("Inserted finance core index information successfully!")
    except Exception as e:
        print(f"Error inserting finance core index data: {e}")

def fetch_and_store_finance_core_index(conn, clear_data):
    try:
        create_finance_core_index_table(conn)

        if clear_data:
            cur = conn.cursor()
            cur.execute("DELETE FROM ok_finance_stock_core_index;")
            conn.commit()
            print("Cleared all finance core index data.")

        all_stocks_df = adata.stock.info.all_code()
        stock_codes = all_stocks_df['stock_code'].tolist()

        for stock_code in stock_codes:
            if not clear_data and finance_core_index_exists(conn, stock_code):
                print(f"Finance core index for {stock_code} already exists, skipping.")
                continue
            
            print(f"Fetching finance core index for stock code: {stock_code}")
            try:
                core_index_data = adata.stock.finance.get_core_index(stock_code=stock_code)

                if core_index_data.empty:
                    print(f"No finance core index information found for stock code: {stock_code}")
                    continue

                insert_finance_core_index(conn, core_index_data)

            except Exception as e:
                print(f"Error fetching finance core index for {stock_code}: {e}")

    except Exception as e:
        print(f"Error fetching or storing finance core index information: {e}")

def main(clear_data=True):
    conn = connect_to_db()
    if conn is None:
        return

    try:
        fetch_and_store_finance_core_index(conn, clear_data)

    finally:
        conn.close()

if __name__ == "__main__":
    main(clear_data=True)  # 设置是否清空数据表数据