import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras

# 单只股票所属概念-ths
# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 创建或清空股票概念信息表
def create_or_clear_stock_concept_table(conn):
    """创建股票概念信息表（如果不存在），或清空表数据"""
    table_name = 'ok_finance_stock_concept_ths'
    try:
        cur = conn.cursor()
        # 检查表是否存在
        cur.execute(sql.SQL("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = %s
            );
        """), (table_name,))
        
        table_exists = cur.fetchone()[0]

        if not table_exists:
            # 创建表
            cur.execute(sql.SQL("""
                CREATE TABLE IF NOT EXISTS {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT,
                    concept_code TEXT,
                    name TEXT,
                    source TEXT,
                    reason TEXT,
                    UNIQUE(stock_code, concept_code)  -- 联合唯一约束
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票所属概念信息';").format(sql.Identifier(table_name)))

            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.concept_code IS '概念代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.name IS '概念名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '信息来源';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.reason IS '概念原因';").format(sql.Identifier(table_name)))

            print(f"Table {table_name} created successfully with comments!")
        else:
            # 如果表存在，则清空数据
            cur.execute(sql.SQL("TRUNCATE TABLE {};").format(sql.Identifier(table_name)))
            print(f"Table {table_name} already exists. Cleared existing data.")
        
        conn.commit()

    except Exception as e:
        print(f"Error creating or clearing table: {e}")

# 插入股票所属概念信息
def insert_stock_concept(conn, concepts):
    """插入股票所属概念信息"""
    try:
        cur = conn.cursor()
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_stock_concept_ths (
                stock_code, concept_code, name, source, reason
            )
            VALUES %s
            ON CONFLICT (stock_code, concept_code) DO NOTHING;  -- 遇冲突则忽略
            """,
            concepts,
            template=None,
            page_size=100
        )
        conn.commit()
        print(f"Inserted {len(concepts)} rows into ok_finance_stock_concept_ths successfully!")
    except Exception as e:
        print(f"Error inserting stock concept data: {e}")

# 获取和存储所有股票的所属概念信息
def fetch_and_store_stock_concepts(conn, all_stocks):
    """获取并存储所有股票的所属概念信息"""
    concepts_data = []

    for _, row in all_stocks.iterrows():
        stock_code = row['stock_code']
        try:
            # 获取所属概念信息
            concepts = adata.stock.info.get_concept_ths(stock_code=stock_code)
            if concepts is not None and not concepts.empty:
                for _, concept in concepts.iterrows():
                    concepts_data.append((stock_code, concept['concept_code'], concept['name'], concept['source'], concept['reason']))
                print(f"Fetched concepts for stock code {stock_code} successfully!")
            else:
                print(f"No concepts found for stock code {stock_code}.")
        except Exception as e:
            print(f"Error fetching concepts for stock code {stock_code}: {e}")

    # 把收集到的概念数据插入数据库
    if concepts_data:
        insert_stock_concept(conn, concepts_data)

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建或清空股票概念信息表
        create_or_clear_stock_concept_table(conn)

        # 获取所有股票信息
        all_stocks = adata.stock.info.all_code()
        print("Fetched all stock code data successfully!")

        # 获取并存储所有股票的所属概念信息
        fetch_and_store_stock_concepts(conn, all_stocks)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()