import adata
import psycopg2
from psycopg2 import sql

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建交易日历信息表（如果不存在）并添加注释
def create_trade_calendar_table(conn):
    table_name = 'ok_finance_trade_calendar'  # 修改为新表名
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    trade_date DATE NOT NULL UNIQUE,  -- 确保trade_date列是唯一的
                    trade_status INT NOT NULL,
                    day_week INT NOT NULL
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储交易日历信息';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '主键ID';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_date IS '交易日';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_status IS '交易状态：0.非交易日；1.交易日';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.day_week IS '一周第几天:从星期天开始的';").format(sql.Identifier(table_name)))

            conn.commit()
            print(f"Table {table_name} created successfully with comments!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 清空交易日历表
def clear_trade_calendar_table(conn):
    table_name = 'ok_finance_trade_calendar'  # 修改为新表名
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("DELETE FROM {};").format(sql.Identifier(table_name)))
        conn.commit()
        print("Existing trade calendar data cleared successfully!")
    except Exception as e:
        print(f"Error clearing trade calendar data: {e}")

# 插入交易日历信息
def insert_trade_calendar(conn, trade_calendar_data):
    table_name = 'ok_finance_trade_calendar'  # 修改为新表名
    try:
        cur = conn.cursor()
        for index, row in trade_calendar_data.iterrows():
            trade_date = row['trade_date']
            trade_status = row['trade_status']
            day_week = row['day_week']
            # 执行插入操作
            try:
                cur.execute(sql.SQL("""
                    INSERT INTO {} (trade_date, trade_status, day_week)
                    VALUES (%s, %s, %s);
                """).format(sql.Identifier(table_name)), (trade_date, trade_status, day_week))
            except psycopg2.IntegrityError:
                print(f"Trade date {trade_date} already exists in the table, skipping insertion.")
                conn.rollback()  # 回滚当前事务，以处理冲突
                continue  # 继续下一个循环

        conn.commit()
        print("Inserted trade calendar information successfully!")
    except Exception as e:
        print(f"Error inserting trade calendar data: {e}")

# 获取并存储交易日历信息
def fetch_and_store_trade_calendar(conn, years):
    try:
        # 清空数据
        clear_trade_calendar_table(conn)

        for year in years:
            # 获取交易日历信息
            trade_calendar_df = adata.stock.info.trade_calendar(year=year)
            print(f"Fetched trade calendar for year {year} successfully!")

            # 插入交易日历数据
            insert_trade_calendar(conn, trade_calendar_df)

    except Exception as e:
        print(f"Error fetching or inserting trade calendar information: {e}")

# 主函数
def main(start_year=2020, end_year=2025):
    years = list(range(start_year, end_year + 1))  # 生成从起始年到结束年的年份列表
    conn = connect_to_db()
    if conn is None:
        return

    try:
        # 创建交易日历信息表
        create_trade_calendar_table(conn)

        # 获取并存储交易日历信息
        fetch_and_store_trade_calendar(conn, years)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main(start_year=2020, end_year=2025)  # 设置起始年份和结束年份