import adata
import psycopg2
from psycopg2 import sql

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建指数成分信息表（如果不存在）并添加注释和索引
def create_index_constituent_table(conn):
    table_name = 'ok_finance_index_constituent'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    index_code TEXT NOT NULL,
                    stock_code TEXT NOT NULL,
                    short_name TEXT NOT NULL,
                    UNIQUE (index_code, stock_code)  -- 确保指数代码和股票代码的组合唯一
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储指数成分信息';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '指数代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.short_name IS '股票简称';").format(sql.Identifier(table_name)))

            # 创建索引以优化查询
            cur.execute(sql.SQL("CREATE INDEX idx_ok_finance_index_constituent_index_code ON {} (index_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_ok_finance_index_constituent_stock_code ON {} (stock_code);").format(sql.Identifier(table_name)))

            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入指数成分信息
def insert_index_constituent(conn, constituent_data):
    try:
        cur = conn.cursor()
        for index, row in constituent_data.iterrows():
            # 确保列存在再进行数据插入
            if 'index_code' in row and 'stock_code' in row and 'short_name' in row:
                index_code = row['index_code']
                stock_code = row['stock_code']
                short_name = row['short_name']
                # 执行插入操作
                cur.execute(sql.SQL("""
                    INSERT INTO ok_finance_index_constituent (index_code, stock_code, short_name)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (index_code, stock_code) DO NOTHING;  -- 避免重复插入
                """), (index_code, stock_code, short_name))
            else:
                print("Warning: Missing columns in the constituent data")

        conn.commit()
        print("Inserted/Updated index constituent information successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取并存储所有指数的成分信息
def fetch_and_store_index_constituents(conn, clear_data):
    try:
        if clear_data:
            cur = conn.cursor()
            cur.execute("DELETE FROM ok_finance_index_constituent;")
            conn.commit()
            print("Existing index constituent data cleared successfully!")

        # 获取所有指数信息
        index_df = adata.stock.info.all_index_code()
        print("Fetched index codes successfully!")

        # 遍历每个指数，获取其成分信息
        for _, row in index_df.iterrows():
            index_code = row['index_code']
            print(f"begin geting for index code: {index_code}")
            try:
                # 获取成分信息
                df_constituent = adata.stock.info.index_constituent(index_code=index_code)

                # 检查 df_constituent 的结构
                if df_constituent.empty:
                    print(f"No constituents found for index code: {index_code}")
                else:
                    print(f"Found {len(df_constituent)} constituents for index code: {index_code}")
                    
                    # 插入数据
                    insert_index_constituent(conn, df_constituent)
            except Exception as e:
                print(f"Error fetching constituents for index code {index_code}: {e}")
        
    except Exception as e:
        print(f"Error fetching or inserting index constituent information: {e}")

# 主函数
def main(clear_data=True):
    conn = connect_to_db()
    if conn is None:
        return

    try:
        # 创建指数成分信息表
        create_index_constituent_table(conn)

        # 获取并存储所有指数的成分信息
        fetch_and_store_index_constituents(conn, clear_data)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main(clear_data=True)  # 设置为 True 或 False 控制是否清空数据