import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建东方财富概念指数信息表（如果不存在）并添加注释
def create_concept_code_east_table(conn):
    table_name = 'ok_finance_concept_code_east'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    concept_code TEXT NOT NULL,
                    index_code TEXT NOT NULL,
                    name TEXT NOT NULL,
                    source TEXT,
                    UNIQUE(concept_code, index_code)
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储东方财富的概念指数信息';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.concept_code IS '概念代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '指数代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.name IS '概念名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '数据来源';").format(sql.Identifier(table_name)))
            
            # 添加索引
            cur.execute(sql.SQL("CREATE INDEX idx_concept_code_east_concept_code ON {} (concept_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_concept_code_east_index_code ON {} (index_code);").format(sql.Identifier(table_name)))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入新的东方财富概念指数信息，之前先清空表
def insert_concept_code_east(conn, concept_data):
    try:
        cur = conn.cursor()
        # 清空表中的所有数据
        cur.execute("DELETE FROM ok_finance_concept_code_east;")
        conn.commit()
        
        print("Existing data cleared successfully!")

        # 使用 execute_values 批量插入
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_concept_code_east (
                concept_code, index_code, name, source
            )
            VALUES %s;
            """,
            [
                (row['concept_code'], row['index_code'], row['name'], row['source'])
                for index, row in concept_data.iterrows()
            ],
            template=None,
            page_size=100
        )
        
        conn.commit()
        print(f"Inserted {len(concept_data)} rows into ok_finance_concept_code_east successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取东方财富概念指数信息
def fetch_concept_code_east():
    try:
        df = adata.stock.info.all_concept_code_east()
        print("Fetched East concept code data successfully!")
        return df
    except Exception as e:
        print(f"Error fetching East concept code data: {e}")
        return None

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建东方财富概念指数信息表（如果不存在）并添加注释
        create_concept_code_east_table(conn)

        # 获取东方财富概念指数信息
        concept_data = fetch_concept_code_east()
        
        if concept_data is not None:
            # 插入新东方财富概念指数信息，清空表后再插入
            insert_concept_code_east(conn, concept_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()