import adata
import pandas as pd
import psycopg2
from psycopg2 import sql
from datetime import datetime
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """
    检查表是否存在
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建 K 线数据表（如果不存在）并添加注释
def create_kline_table(conn, table_name):
    """
    创建 K 线数据表（如果不存在）并添加注释
    """
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT NOT NULL,
                    trade_time VARCHAR(64) NOT NULL,
                    trade_date VARCHAR(64) NOT NULL,
                    open NUMERIC(20,6),
                    close NUMERIC(20,6),
                    high NUMERIC(20,6),
                    low NUMERIC(20,6),
                    volume BIGINT,
                    amount NUMERIC(20,6),
                    change_pct NUMERIC(20,6),
                    change NUMERIC(20,6),
                    turnover_ratio NUMERIC(20,6),
                    pre_close NUMERIC(20,6),
                    UNIQUE(stock_code, trade_date)
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储所有股票的日K线数据';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_time IS '交易时间（字符串格式）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_date IS '交易日期（字符串格式）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.open IS '开盘价（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.close IS '收盘价（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.high IS '最高价（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.low IS '最低价（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.volume IS '成交量';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.amount IS '成交额（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_pct IS '涨跌幅百分比（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change IS '涨跌额（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.turnover_ratio IS '换手率（高精度数值）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.pre_close IS '前收盘价（高精度数值）';").format(sql.Identifier(table_name)))
            
            # 添加索引（为索引名称添加表名前缀）
            index_prefix = table_name.replace('ok_finance_kline_', 'idx_')  # 例如：daily -> idx_daily
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (stock_code);").format(
                sql.Identifier(index_prefix + '_stock_code'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (trade_date);").format(
                sql.Identifier(index_prefix + '_trade_date'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (stock_code, trade_date);").format(
                sql.Identifier(index_prefix + '_stock_code_trade_date'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 获取某只股票的最新交易日
def get_latest_trade_date(conn, table_name, stock_code):
    """
    获取某只股票的最新交易日
    """
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            SELECT MAX(trade_date)
            FROM {}
            WHERE stock_code = %s;
        """).format(sql.Identifier(table_name)), (stock_code,))
        latest_date = cur.fetchone()[0]
        return latest_date
    except Exception as e:
        print(f"Error getting latest trade date: {e}")
        return None

# 插入或更新 K 线数据
def insert_kline_data(conn, table_name, stock_code, kline_data):
    """
    插入或更新 K 线数据（直接使用原始数据）
    """
    try:
        cur = conn.cursor()
        for index, row in kline_data.iterrows():  # 直接遍历原始数据
            # 保留数值精度处理
            cur.execute(sql.SQL("""
                INSERT INTO {} (
                    stock_code, trade_time, trade_date, open, close, high, low,
                    volume, amount, change_pct, change, turnover_ratio, pre_close
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (stock_code, trade_date) DO UPDATE
                SET
                    trade_time = EXCLUDED.trade_time,
                    open = EXCLUDED.open,
                    close = EXCLUDED.close,
                    high = EXCLUDED.high,
                    low = EXCLUDED.low,
                    volume = EXCLUDED.volume,
                    amount = EXCLUDED.amount,
                    change_pct = EXCLUDED.change_pct,
                    change = EXCLUDED.change,
                    turnover_ratio = EXCLUDED.turnover_ratio,
                    pre_close = EXCLUDED.pre_close;
            """).format(sql.Identifier(table_name)), 
            (
                stock_code, 
                str(row['trade_time']),
                str(row['trade_date']),
                round(float(row['open']), 6) if pd.notnull(row['open']) else None,
                round(float(row['close']), 6) if pd.notnull(row['close']) else None,
                round(float(row['high']), 6) if pd.notnull(row['high']) else None,
                round(float(row['low']), 6) if pd.notnull(row['low']) else None,
                row['volume'],
                round(float(row['amount']), 6) if pd.notnull(row['amount']) else None,
                round(float(row['change_pct']), 6) if pd.notnull(row['change_pct']) else None,
                round(float(row['change']), 6) if pd.notnull(row['change']) else None,
                round(float(row['turnover_ratio']), 6) if pd.notnull(row['turnover_ratio']) else None,
                round(float(row['pre_close']), 6) if pd.notnull(row['pre_close']) else None
            ))
        conn.commit()
        print(f"Upserted {len(kline_data)} rows into {table_name} for stock {stock_code} successfully!")
    except Exception as e:
        print(f"Error upserting data: {e}")

# 获取股票的 K 线数据
def fetch_kline_data(stock_code, k_type, start_date):
    try:
        res_df = adata.stock.market.get_market(stock_code=stock_code, k_type=k_type, start_date=start_date)
        print(f"Fetched {k_type} K-line data for stock {stock_code} successfully!")
        return res_df
    except Exception as e:
        print(f"Error fetching {k_type} K-line data for stock {stock_code}: {e}")
        return None

# 主函数
def main():
    # 表名
    daily_table = 'ok_finance_kline_daily'
    weekly_table = 'ok_finance_kline_weekly'
    monthly_table = 'ok_finance_kline_monthly'

    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建 K 线数据表（如果不存在）并添加注释
        create_kline_table(conn, daily_table)
        create_kline_table(conn, weekly_table)
        create_kline_table(conn, monthly_table)

        # 获取所有股票代码
        # stocks_df = adata.stock.info.all_code()


        # 创建一个包含固定股票代码的 DataFrame 用于测试
        stocks_df = pd.DataFrame({
            'stock_code': ['000001', '600000']  # 示例股票代码
        })
        if stocks_df is None:
            return
        
        # 遍历所有股票代码
        for index, row in stocks_df.iterrows():
            stock_code = row['stock_code']
            
            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, daily_table, stock_code)
            
            # 如果存在最新交易日，则从该日期开始更新；否则从 2020 年开始插入
            start_date = latest_date if latest_date else '2025-03-01'
            
            # 获取日K数据并插入
            daily_data = fetch_kline_data(stock_code, k_type=1, start_date=start_date)
            if daily_data is not None:
                insert_kline_data(conn, daily_table, stock_code, daily_data)

            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, weekly_table, stock_code)
            
            # 如果存在最新交易日，则从该日期开始更新；否则从 2020 年开始插入
            start_date = latest_date if latest_date else '2025-03-01'
            
            # 获取日K数据并插入
            daily_data = fetch_kline_data(stock_code, k_type=2, start_date=start_date)
            if daily_data is not None:
                insert_kline_data(conn, weekly_table, stock_code, daily_data)

            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, monthly_table, stock_code)
            
            # 如果存在最新交易日，则从该日期开始更新；否则从 2020 年开始插入
            start_date = latest_date if latest_date else '2025-03-01'
            
            # 获取日K数据并插入
            daily_data = fetch_kline_data(stock_code, k_type=3, start_date=start_date)
            if daily_data is not None:
                insert_kline_data(conn, monthly_table, stock_code, daily_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()