import adata
import psycopg2
from psycopg2 import sql, extras

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建东方财富概念指数成分信息表（如果不存在）并添加注释
def create_concept_constituent_east_table(conn):
    table_name = 'ok_finance_concept_constituent_east'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    concept_code TEXT NOT NULL,
                    stock_code TEXT NOT NULL,
                    short_name TEXT NOT NULL
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储东方财富的概念指数成分信息';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.concept_code IS '关联概念代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.short_name IS '股票简称';").format(sql.Identifier(table_name)))
            
            # 添加索引
            cur.execute(sql.SQL("CREATE INDEX idx_concept_constituent_code ON {} (concept_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_concept_constituent_stock_code ON {} (stock_code);").format(sql.Identifier(table_name)))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入新的东方财富概念指数成分信息，之前先清空表
def insert_concept_constituent_east(conn, concept_constituent_data, concept_code):
    try:
        cur = conn.cursor()
        # 清空表中的特定概念代码的成分数据
        cur.execute("DELETE FROM ok_finance_concept_constituent_east WHERE concept_code = %s;", (concept_code,))
        conn.commit()
        
        print(f"Existing data for concept code {concept_code} cleared successfully!")

        # 使用 execute_values 批量插入
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_concept_constituent_east (
                concept_code, stock_code, short_name
            )
            VALUES %s;
            """,
            [
                (concept_code, row['stock_code'], row['short_name'])
                for index, row in concept_constituent_data.iterrows()
            ],
            template=None,
            page_size=100
        )
        
        conn.commit()
        print(f"Inserted {len(concept_constituent_data)} rows into ok_finance_concept_constituent_east successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取并插入东方财富概念指数成分信息
def fetch_and_store_concept_constituents(conn, concept_code_list):
    for concept_code in concept_code_list:
        try:
            df = adata.stock.info.concept_constituent_east(concept_code=concept_code)
            print(f"Fetched constituent data for concept code {concept_code} successfully!")
            # 插入新东方财富概念指数成分信息
            insert_concept_constituent_east(conn, df, concept_code)
        except Exception as e:
            print(f"Error fetching or inserting data for concept code {concept_code}: {e}")

# 获取东方财富概念指数信息
def fetch_concept_code_east():
    try:
        df = adata.stock.info.all_concept_code_east()
        print("Fetched East concept code data successfully!")
        return df
    except Exception as e:
        print(f"Error fetching East concept code data: {e}")
        return None

# 主函数
def main():
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建东方财富概念指数成分信息表（如果不存在）并添加注释
        create_concept_constituent_east_table(conn)

        # 获取所有的概念代码数据
        concept_code_data = fetch_concept_code_east()

        if concept_code_data is not None:
            # 获取概念代码列表
            concept_code_list = concept_code_data['concept_code'].tolist()
            # 为每个概念代码获取并存储成分信息
            fetch_and_store_concept_constituents(conn, concept_code_list)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()