import adata
import pandas as pd
import psycopg2
from psycopg2 import sql
from datetime import datetime
import os

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """
    检查表是否存在
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建 K 线数据表（如果不存在）并添加注释
def create_kline_table(conn, table_name):
    """
    创建 K 线数据表（如果不存在）并添加注释
    """
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT NOT NULL,
                    trade_time TIMESTAMP NOT NULL,
                    trade_date DATE NOT NULL,
                    open FLOAT,
                    close FLOAT,
                    high FLOAT,
                    low FLOAT,
                    volume BIGINT,
                    amount FLOAT,
                    change_pct FLOAT,
                    change FLOAT,
                    turnover_ratio FLOAT,
                    pre_close FLOAT,
                    UNIQUE(stock_code, trade_date)
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储所有股票的日K线数据';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_time IS '交易时间';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.trade_date IS '交易日期';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.open IS '开盘价';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.close IS '收盘价';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.high IS '最高价';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.low IS '最低价';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.volume IS '成交量';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.amount IS '成交额';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_pct IS '涨跌幅百分比';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change IS '涨跌额';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.turnover_ratio IS '换手率';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.pre_close IS '前收盘价';").format(sql.Identifier(table_name)))
            # 添加索引（为索引名称添加表名前缀）
            index_prefix = table_name.replace('ok_finance_kline_', 'idx_')  # 例如：daily -> idx_daily
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (stock_code);").format(
                sql.Identifier(index_prefix + '_stock_code'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (trade_date);").format(
                sql.Identifier(index_prefix + '_trade_date'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            cur.execute(sql.SQL("CREATE INDEX {} ON {} (stock_code, trade_date);").format(
                sql.Identifier(index_prefix + '_stock_code_trade_date'),  # 索引名称
                sql.Identifier(table_name)  # 表名
            ))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 获取某只股票的最新交易日
def get_latest_trade_date(conn, table_name, stock_code):
    """
    获取某只股票的最新交易日
    """
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            SELECT MAX(trade_date)
            FROM {}
            WHERE stock_code = %s;
        """).format(sql.Identifier(table_name)), (stock_code,))
        latest_date = cur.fetchone()[0]
        return latest_date
    except Exception as e:
        print(f"Error getting latest trade date: {e}")
        return None

# 删除某只股票的最新交易日数据
def delete_latest_trade_date(conn, table_name, stock_code):
    """
    删除某只股票的最新交易日数据
    """
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            DELETE FROM {}
            WHERE stock_code = %s
            AND trade_date = (
                SELECT MAX(trade_date)
                FROM {}
                WHERE stock_code = %s
            );
        """).format(
            sql.Identifier(table_name),  # 第一个格式化参数：表名
            sql.Identifier(table_name)   # 第二个格式化参数：表名
        ), (stock_code, stock_code))  # SQL 参数：stock_code 和 stock_code
        conn.commit()
        print(f"Deleted latest trade date data for stock {stock_code} in {table_name}.")
    except Exception as e:
        print(f"Error deleting latest trade date data: {e}")

# 清理数据并保存无效数据到 CSV 文件
def clean_and_save_invalid_data(kline_data, stock_code, table_name):
    """
    清理数据并保存无效数据到 CSV 文件
    """
    invalid_data = []
    cleaned_data = []

    for index, row in kline_data.iterrows():
        # 检查 trade_date 是否为空或无效
        if pd.isna(row['trade_date']) or row['trade_date'] == '':
            invalid_data.append(row)
            continue

        # 检查其他字段是否为空或无效
        if (pd.isna(row['open']) or pd.isna(row['close']) or pd.isna(row['high']) or
            pd.isna(row['low']) or pd.isna(row['volume']) or pd.isna(row['amount']) or
            pd.isna(row['change_pct']) or pd.isna(row['change']) or pd.isna(row['turnover_ratio']) or
            pd.isna(row['pre_close'])):
            invalid_data.append(row)
            continue

        # 如果数据有效，则添加到 cleaned_data
        cleaned_data.append(row)

    # 如果有无效数据，则保存到 CSV 文件
    if invalid_data:
        invalid_df = pd.DataFrame(invalid_data)
        invalid_file = f"invalid_data_{stock_code}_{table_name}.csv"
        invalid_df.to_csv(invalid_file, index=False)
        print(f"Saved {len(invalid_data)} invalid rows to {invalid_file}")

    # 返回清理后的数据
    return pd.DataFrame(cleaned_data)

# 插入或更新 K 线数据
def insert_kline_data(conn, table_name, stock_code, kline_data):
    """
    插入或更新 K 线数据
    - 如果股票代码存在，则更新数据。
    - 如果股票代码不存在，则插入新数据。
    """
    try:
        # 清理数据并保存无效数据
        cleaned_data = clean_and_save_invalid_data(kline_data, stock_code, table_name)

        # 插入或更新清理后的数据
        cur = conn.cursor()
        for index, row in cleaned_data.iterrows():
            cur.execute(sql.SQL("""
                INSERT INTO {} (
                    stock_code, trade_time, trade_date, open, close, high, low,
                    volume, amount, change_pct, change, turnover_ratio, pre_close
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (stock_code, trade_date) DO UPDATE
                SET
                    trade_time = EXCLUDED.trade_time,
                    open = EXCLUDED.open,
                    close = EXCLUDED.close,
                    high = EXCLUDED.high,
                    low = EXCLUDED.low,
                    volume = EXCLUDED.volume,
                    amount = EXCLUDED.amount,
                    change_pct = EXCLUDED.change_pct,
                    change = EXCLUDED.change,
                    turnover_ratio = EXCLUDED.turnover_ratio,
                    pre_close = EXCLUDED.pre_close;
            """).format(sql.Identifier(table_name)), 
            (
                stock_code, row['trade_time'], row['trade_date'], row['open'], row['close'],
                row['high'], row['low'], row['volume'], row['amount'], row['change_pct'],
                row['change'], row['turnover_ratio'], row['pre_close']
            ))
        conn.commit()
        print(f"Upserted {len(cleaned_data)} rows into {table_name} for stock {stock_code} successfully!")
    except Exception as e:
        print(f"Error upserting data: {e}")

# 获取股票的 K 线数据
def fetch_kline_data(stock_code, k_type, start_date):
    try:
        res_df = adata.stock.market.get_market(stock_code=stock_code, k_type=k_type, start_date=str(start_date))
        print(f"Fetched {k_type} K-line data for stock: {stock_code} date: {start_date} count: {len(res_df)} successfully!")
        return res_df
    except Exception as e:
        print(f"Error fetching {k_type} K-line data for stock {stock_code}: {e}")
        return None

# 主函数
def main():
    # 表名
    daily_table = 'ok_finance_kline_daily'
    weekly_table = 'ok_finance_kline_weekly'
    monthly_table = 'ok_finance_kline_monthly'

    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建 K 线数据表（如果不存在）并添加注释
        create_kline_table(conn, daily_table)
        create_kline_table(conn, weekly_table)
        create_kline_table(conn, monthly_table)

        # 获取所有股票代码
        stocks_df = adata.stock.info.all_code()

        # 创建一个包含固定股票代码的 DataFrame 用于测试
        # stocks_df = pd.DataFrame({
        #     'stock_code': ['000001', '600000']  # 示例股票代码
        # })
        if stocks_df is None:
            return
        
        # 遍历所有股票代码
        for index, row in stocks_df.iterrows():
            stock_code = row['stock_code']
            
            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, daily_table, stock_code)
            if latest_date is None:
                # 如果存在最新交易日，则从该日期开始更新；否则从 2020 年开始插入
                start_date = latest_date if latest_date else '2020-01-01'
                
                # 获取日K数据并插入
                daily_data = fetch_kline_data(stock_code, k_type=1, start_date=start_date)
                if daily_data is not None:
                    insert_kline_data(conn, daily_table, stock_code, daily_data)

            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, weekly_table, stock_code)
            if latest_date is None:
                # 如果存在最新交易日，则删除最新交易日的数据
                if latest_date:
                    delete_latest_trade_date(conn, weekly_table, stock_code)

                # 再次获取当前股票的最新交易日
                latest_date = get_latest_trade_date(conn, weekly_table, stock_code)
                print("weekly_table latest_date {}",latest_date)

                # 从最新交易日开始更新数据
                start_date = latest_date if latest_date else '2020-01-01'
                
                # 获取周K数据并插入
                weekly_data = fetch_kline_data(stock_code, k_type=2, start_date=start_date)
                if weekly_data is not None:
                    insert_kline_data(conn, weekly_table, stock_code, weekly_data)

            # 获取当前股票的最新交易日
            latest_date = get_latest_trade_date(conn, monthly_table, stock_code)
            if latest_date is None:
                # 如果存在最新交易日，则删除最新交易日的数据
                if latest_date:
                    delete_latest_trade_date(conn, monthly_table, stock_code)
                
                # 再次获取当前股票的最新交易日
                latest_date = get_latest_trade_date(conn, monthly_table, stock_code)
                print("monthly_table latest_date {}",latest_date)
                
                # 从最新交易日开始更新数据
                start_date = latest_date if latest_date else '2020-01-01'
                
                # 获取月K数据并插入
                monthly_data = fetch_kline_data(stock_code, k_type=3, start_date=start_date)

                if monthly_data is not None:
                    insert_kline_data(conn, monthly_table, stock_code, monthly_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()