import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
import time  # 用于控制请求间隔

# 概念指数成分信息-ths
# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 创建概念成分信息表（如果不存在）并添加注释
def create_concept_constituent_table(conn):
    """创建概念成分信息表（如果不存在）并添加注释"""
    table_name = 'ok_finance_concept_constituent_ths'
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            CREATE TABLE IF NOT EXISTS {} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                index_code TEXT,
                stock_code TEXT,
                short_name TEXT,
                UNIQUE(stock_code, index_code)  -- 联合唯一约束
            );
        """).format(sql.Identifier(table_name)))

        # 添加表注释
        cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储概念成分信息';").format(sql.Identifier(table_name)))

        # 添加字段注释
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键';").format(sql.Identifier(table_name)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '概念指数代码';").format(sql.Identifier(table_name)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.short_name IS '股票名称';").format(sql.Identifier(table_name)))

        conn.commit()
        print(f"Table {table_name} created successfully with comments!")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入概念成分信息
def insert_concept_constituent(conn, constituents):
    """插入概念成分信息"""
    try:
        cur = conn.cursor()
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_concept_constituent_ths (
                index_code, stock_code, short_name
            )
            VALUES %s
            ON CONFLICT (stock_code, index_code) DO NOTHING;  -- 遇冲突则忽略
            """,
            constituents,
            template=None,
            page_size=100
        )
        conn.commit()
        print(f"Inserted {len(constituents)} rows into ok_finance_concept_constituent_ths successfully!")
    except Exception as e:
        print(f"Error inserting constituent data: {e}")

# 检查是否存在某个 index_code 或 concept_code
def check_exist(conn, code, code_type='index'):
    """检查表中是否存在给定的 index_code 或 concept_code"""
    if pd.isna(code) or code == "":
        return False  # 如果是 NaN 或空字符串，直接返回 False
    
    try:
        cur = conn.cursor()
        if code_type == 'index':
            cur.execute("SELECT EXISTS(SELECT 1 FROM ok_finance_concept_constituent_ths WHERE index_code = %s);", (code,))
        else:
            cur.execute("SELECT EXISTS(SELECT 1 FROM ok_finance_concept_constituent_ths WHERE stock_code = %s);", (code,))
        
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking existence of {code_type} '{code}': {e}")
        return False

# 获取概念成分信息
def fetch_and_store_constituents(conn, concept_data, wait_time=0):
    """获取并存储概念成分信息"""
    constituents_data = []

    for _, row in concept_data.iterrows():
        index_code = row['index_code']
        concept_code = row['concept_code']
        
        if pd.isna(index_code) or index_code == "":
            print(f"Index code for concept '{row['name']}' is invalid or empty, checking concept_code...")
            index_code = None  # 将 index_code 置为 None，以便只查询 concept_code
        
        # 尝试根据 index_code 获取成分信息
        if index_code and not check_exist(conn, index_code):
            try:
                constituents = adata.stock.info.concept_constituent_ths(index_code=index_code, wait_time=wait_time)
                if not constituents.empty:
                    for _, constituent in constituents.iterrows():
                        constituents_data.append((index_code, constituent['stock_code'], constituent['short_name']))
                    print(f"Fetched constituents for index code {index_code} successfully!")
                    continue  # 如果找到index_code的成分，直接跳过到下一个概念
            except Exception as e:
                print(f"Error fetching constituency for index code {index_code}: {e}")
        
        # 如果没有找到 constituents, 根据 concept_code 获取成分信息
        if concept_code and not check_exist(conn, concept_code):
            try:
                constituents = adata.stock.info.concept_constituent_ths(concept_code=concept_code, wait_time=wait_time)
                if not constituents.empty:
                    for _, constituent in constituents.iterrows():
                        constituents_data.append((None, constituent['stock_code'], constituent['short_name']))  # 保存为 None 的 index_code
                    print(f"Fetched constituents for concept code {concept_code} successfully!")
            except Exception as e:
                print(f"Error fetching constituency for concept code {concept_code}: {e}")

    # 把收集到的成分数据插入数据库
    if constituents_data:
        insert_concept_constituent(conn, constituents_data)

# 主函数
def main(wait_time=0):
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建概念成分信息表
        create_concept_constituent_table(conn)

        # 获取所有概念信息
        concept_data = adata.stock.info.all_concept_code_ths()
        print("Fetched all concept code data successfully!")

        # 获取并存储各概念的成分信息
        fetch_and_store_constituents(conn, concept_data, wait_time=wait_time)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    # 控制请求间隔时间
    main(wait_time=1000)  # 例如：等待 1000 毫秒（1秒）