import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 全局配置
DB_CONFIG = {
    'dbname': 'ocean_kite',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

TABLE_NAME = 'ok_finance_stock_shares'
PREFIX = 'ok_finance_stock_'

def generate_index_name(column_name):
    """生成标准化索引名称：idx_<简化的表名>_<字段名>"""
    stripped_table = TABLE_NAME.replace(PREFIX, "", 1)
    return f"idx_{stripped_table}_{column_name}"

def connect_to_db():
    """连接数据库（保留原始注释）"""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("数据库连接成功!")
        return conn
    except Exception as e:
        print(f"数据库连接失败: {e}")
        return None

def create_stock_shares_table(conn):
    """创建/更新表结构（带动态索引）"""
    try:
        with conn.cursor() as cur:
            # 动态建表
            cur.execute(sql.SQL("""
                CREATE TABLE IF NOT EXISTS {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code VARCHAR(64) NOT NULL,
                    total_shares NUMERIC(20, 0),
                    limit_shares NUMERIC(20, 0),
                    list_a_shares NUMERIC(20, 0),
                    change_reason VARCHAR(64),
                    change_date VARCHAR(64) NOT NULL,
                    UNIQUE(stock_code, change_date)
                );
            """).format(sql.Identifier(TABLE_NAME)))

            # 动态创建索引
            indexes = [
                ("stock_code", "stock_code"),
                ("change_date", "change_date"),
                ("composite", "stock_code, change_date")
            ]
            for idx_type, columns in indexes:
                idx_name = generate_index_name(idx_type)
                cur.execute(sql.SQL("""
                    CREATE INDEX IF NOT EXISTS {} ON {} ({})
                """).format(
                    sql.Identifier(idx_name),
                    sql.Identifier(TABLE_NAME),
                    sql.SQL(columns)
                ))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票股本变动信息'").format(sql.Identifier(TABLE_NAME)))
            
            # 字段注释配置
            comments = {
                'stock_code': '股票代码',
                'total_shares': '总股本',
                'limit_shares': '限售股份',
                'list_a_shares': '流通A股',
                'change_reason': '变更原因',
                'change_date': '变更日期（YYYY-MM-DD格式字符串）'
            }
            for col, comment in comments.items():
                cur.execute(sql.SQL("COMMENT ON COLUMN {}.{} IS %s").format(
                    sql.Identifier(TABLE_NAME),
                    sql.Identifier(col)
                ), (comment,))
                
        conn.commit()
        print(f"表 {TABLE_NAME} 初始化完成")
    except Exception as e:
        print(f"表操作异常: {e}")
        conn.rollback()

def has_stock_data(conn, stock_code):
    """存在性检查（带动态表名）"""
    try:
        with conn.cursor() as cur:
            cur.execute(sql.SQL("""
                SELECT EXISTS (
                    SELECT 1 FROM {}
                    WHERE stock_code = %s
                )
            """).format(sql.Identifier(TABLE_NAME)), (stock_code,))
            return cur.fetchone()[0]
    except Exception as e:
        print(f"存在性检查失败: {e}")
        return False

def process_stock_shares(conn, stock_code):
    """处理单个股票的股本数据"""
    try:
        # 获取数据（测试时强制获取历史数据）
        shares_data = adata.stock.info.get_stock_shares(stock_code=stock_code, is_history=True)
        
        if shares_data is None or shares_data.empty:
            print(f"无股本数据 {stock_code}")
            return
            
        # 数据清洗
        shares_data['change_date'] = shares_data['change_date'].astype(str).str[:10]
        shares_data['change_reason'] = shares_data['change_reason'].str.slice(0, 64)
        numeric_cols = ['total_shares', 'limit_shares', 'list_a_shares']
        
        # 使用 map 替代 applymap
        for col in numeric_cols:
            shares_data[col] = shares_data[col].map(
                lambda x: round(x) if pd.notnull(x) else None
            )

        # 批量插入
        with conn.cursor() as cur:
            data = [
                (
                    stock_code,
                    row['total_shares'],
                    row['limit_shares'],
                    row['list_a_shares'],
                    row['change_reason'],
                    row['change_date']
                )
                for _, row in shares_data.iterrows()
            ]
            
            extras.execute_values(
                cur,
                sql.SQL("""
                    INSERT INTO {} (
                        stock_code, total_shares, limit_shares, 
                        list_a_shares, change_reason, change_date
                    ) VALUES %s
                    ON CONFLICT (stock_code, change_date) DO UPDATE SET
                        total_shares = EXCLUDED.total_shares,
                        limit_shares = EXCLUDED.limit_shares,
                        list_a_shares = EXCLUDED.list_a_shares,
                        change_reason = EXCLUDED.change_reason
                """).format(sql.Identifier(TABLE_NAME)),
                data,
                page_size=500
            )
        conn.commit()
        print(f"成功更新 {stock_code} 股本数据 {len(data)} 条")
    except Exception as e:
        print(f"数据处理失败: {e}")
        conn.rollback()

def main():
    conn = connect_to_db()
    if not conn:
        return

    try:
        create_stock_shares_table(conn)
        
        # 正式环境使用（保留注释）
        # stocks_df = adata.stock.info.all_code()
        
        # 测试数据（正式环境需注释）
        stocks_df = adata.stock.info.all_code().head(10)
        
        # 处理每个股票
        for stock_code in stocks_df['stock_code']:
            if not has_stock_data(conn, stock_code):
                process_stock_shares(conn, stock_code)
                
    except Exception as e:
        print(f"主流程异常: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    main()