import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 全局配置
DB_CONFIG = {
    'dbname': 'ocean_kite',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

# K线表配置
KLINE_TABLES = {
    'daily': {
        'name': 'ok_finance_stock_kline_daily',
        'k_type': 1
    },
    'weekly': {
        'name': 'ok_finance_stock_kline_weekly',
        'k_type': 2
    },
    'monthly': {
        'name': 'ok_finance_stock_kline_monthly',
        'k_type': 3
    }
}

PREFIX = 'ok_finance_stock_kline_'

def generate_index_name(table_name, column_name):
    """生成标准化索引名称：idx_<简化的表名>_<字段名>"""
    stripped_table = table_name.replace(PREFIX, "", 1)
    return f"idx_{stripped_table}_{column_name}"

def connect_to_db():
    """连接数据库（保留原始注释）"""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("数据库连接成功!")
        return conn
    except Exception as e:
        print(f"数据库连接失败: {e}")
        return None

def create_kline_table(conn, table_name):
    """通用K线表创建函数"""
    try:
        with conn.cursor() as cur:
            # 建表语句
            cur.execute(sql.SQL("""
                CREATE TABLE IF NOT EXISTS {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code VARCHAR(64) NOT NULL,
                    trade_time VARCHAR(64) NOT NULL,
                    trade_date VARCHAR(64) NOT NULL,
                    open NUMERIC(20,6),
                    close NUMERIC(20,6),
                    high NUMERIC(20,6),
                    low NUMERIC(20,6),
                    volume NUMERIC(20,0),
                    amount NUMERIC(20,6),
                    change_pct NUMERIC(20,6),
                    change NUMERIC(20,6),
                    turnover_ratio NUMERIC(20,6),
                    pre_close NUMERIC(20,6),
                    UNIQUE(stock_code, trade_date)
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票K线数据（{}）';")
                        .format(sql.Identifier(table_name), 
                                sql.SQL('日线' if 'daily' in table_name else '周线' if 'weekly' in table_name else '月线')))

            # 字段注释配置
            comments = {
                'stock_code': '股票代码',
                'trade_time': '交易时间',
                'trade_date': '交易日期',
                'open': '开盘价',
                'close': '收盘价',
                'high': '最高价',
                'low': '最低价',
                'volume': '成交量',
                'amount': '成交额',
                'change_pct': '涨跌幅百分比',
                'change': '涨跌额',
                'turnover_ratio': '换手率',
                'pre_close': '前收盘价'
            }
            for col, comment in comments.items():
                cur.execute(sql.SQL("COMMENT ON COLUMN {}.{} IS %s")
                            .format(sql.Identifier(table_name), sql.Identifier(col)), (comment,))

            # 动态创建索引
            indexes = [
                ("stock_code", "stock_code"),
                ("trade_date", "trade_date"),
                ("composite", "stock_code, trade_date")
            ]
            for idx_type, columns in indexes:
                idx_name = generate_index_name(table_name, idx_type)
                cur.execute(sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} ({})")
                            .format(sql.Identifier(idx_name),
                                    sql.Identifier(table_name),
                                    sql.SQL(columns)))

        conn.commit()
        print(f"表 {table_name} 初始化完成")
    except Exception as e:
        print(f"表操作异常: {e}")
        conn.rollback()

def get_latest_trade_date(conn, table_name, stock_code):
    """通用最新交易日查询"""
    try:
        with conn.cursor() as cur:
            cur.execute(sql.SQL("""
                SELECT MAX(trade_date) FROM {} 
                WHERE stock_code = %s
            """).format(sql.Identifier(table_name)), (stock_code,))
            return cur.fetchone()[0]
    except Exception as e:
        print(f"最新日期查询失败: {e}")
        return None

def process_kline_data(conn, stock_code, table_config):
    """处理单个K线类型数据"""
    table_name = table_config['name']
    k_type = table_config['k_type']
    
    # 获取最新日期
    latest_date = get_latest_trade_date(conn, table_name, stock_code)
    start_date = latest_date if latest_date else '2020-01-01'
    
    # 获取数据
    kline_df = adata.stock.market.get_market(
        stock_code=stock_code, 
        k_type=k_type, 
        start_date=start_date
    )
    
    if kline_df is None or kline_df.empty:
        print(f"无新数据 {table_name} 股票 {stock_code}")
        return
    
    # 数据清洗
    numeric_cols = ['open', 'close', 'high', 'low', 'volume', 'amount',
                    'change_pct', 'change', 'turnover_ratio', 'pre_close']
    kline_df[numeric_cols] = kline_df[numeric_cols].apply(pd.to_numeric, errors='coerce')
    
    # 批量插入
    try:
        with conn.cursor() as cur:
            data = [
                (
                    stock_code,
                    str(row['trade_time']),
                    str(row['trade_date']),
                    round(row['open'], 6) if pd.notnull(row['open']) else None,
                    round(row['close'], 6) if pd.notnull(row['close']) else None,
                    round(row['high'], 6) if pd.notnull(row['high']) else None,
                    round(row['low'], 6) if pd.notnull(row['low']) else None,
                    round(row['volume'], 0) if pd.notnull(row['volume']) else None,
                    round(row['amount'], 6) if pd.notnull(row['amount']) else None,
                    round(row['change_pct'], 6) if pd.notnull(row['change_pct']) else None,
                    round(row['change'], 6) if pd.notnull(row['change']) else None,
                    round(row['turnover_ratio'], 6) if pd.notnull(row['turnover_ratio']) else None,
                    round(row['pre_close'], 6) if pd.notnull(row['pre_close']) else None
                )
                for _, row in kline_df.iterrows()
            ]
            
            extras.execute_values(
                cur,
                sql.SQL("""
                    INSERT INTO {} (
                        stock_code, trade_time, trade_date, 
                        open, close, high, low, volume, amount,
                        change_pct, change, turnover_ratio, pre_close
                    ) VALUES %s
                    ON CONFLICT (stock_code, trade_date) DO UPDATE SET
                        trade_time = EXCLUDED.trade_time,
                        open = EXCLUDED.open,
                        close = EXCLUDED.close,
                        high = EXCLUDED.high,
                        low = EXCLUDED.low,
                        volume = EXCLUDED.volume,
                        amount = EXCLUDED.amount,
                        change_pct = EXCLUDED.change_pct,
                        change = EXCLUDED.change,
                        turnover_ratio = EXCLUDED.turnover_ratio,
                        pre_close = EXCLUDED.pre_close
                """).format(sql.Identifier(table_name)),
                data,
                page_size=500
            )
        conn.commit()
        print(f"成功更新 {table_name} 数据 {len(data)} 条")
    except Exception as e:
        print(f"数据插入失败: {e}")
        conn.rollback()

def main():
    conn = connect_to_db()
    if not conn:
        return

    try:
        # 初始化所有K线表
        for table_config in KLINE_TABLES.values():
            create_kline_table(conn, table_config['name'])
        
        # 正式环境使用（保留注释）
        # stocks_df = adata.stock.info.all_code()
        
        # 测试数据（正式环境需注释）
        stocks_df = pd.DataFrame({'stock_code': ['000001', '600000']})
        
        # 处理每个股票
        for stock_code in stocks_df['stock_code']:
            print(f"\n处理股票 {stock_code}")
            for table_type in ['daily', 'weekly', 'monthly']:
                process_kline_data(conn, stock_code, KLINE_TABLES[table_type])
                
    except Exception as e:
        print(f"主流程异常: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    main()