import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 全局配置
DB_CONFIG = {
    'dbname': 'ocean_kite',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

TABLE_NAME = 'ok_finance_stock_industry_sw'
PREFIX = 'ok_finance_stock_'

def generate_index_name(column_name):
    """生成标准化索引名称：idx_<简化的表名>_<字段名>"""
    stripped_table = TABLE_NAME.replace(PREFIX, "", 1)
    return f"idx_{stripped_table}_{column_name}"

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to database successfully!")
        return conn
    except Exception as e:
        print(f"Database connection error: {e}")
        return None

# 创建行业信息表（带动态索引）
def create_industry_sw_table(conn):
    try:
        cur = conn.cursor()
        
        # 动态建表
        cur.execute(sql.SQL("""
            CREATE TABLE IF NOT EXISTS {} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                stock_code VARCHAR(64) NOT NULL,
                sw_code VARCHAR(64) NOT NULL,
                industry_name VARCHAR(64) NOT NULL,
                industry_type VARCHAR(64) NOT NULL,
                source VARCHAR(64),
                UNIQUE(stock_code, sw_code, industry_type)
            );
        """).format(sql.Identifier(TABLE_NAME)))

        # 动态创建索引
        indexes = [
            ("stock_code", "stock_code"),
            ("sw_code", "sw_code"),
            ("industry_type", "industry_type"),
            ("composite", "stock_code, sw_code, industry_type")
        ]
        
        for idx_type, columns in indexes:
            idx_name = generate_index_name(idx_type)
            cur.execute(sql.SQL("""
                CREATE INDEX IF NOT EXISTS {} ON {} ({})
            """).format(
                sql.Identifier(idx_name),
                sql.Identifier(TABLE_NAME),
                sql.SQL(columns)
            ))

        # 添加表注释
        cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票的申万行业分类信息'").format(sql.Identifier(TABLE_NAME)))
        
        # 字段注释
        field_comments = {
            'id': '自增主键，从 1000 开始',
            'stock_code': '股票代码',
            'sw_code': '申万行业代码',
            'industry_name': '行业名称',
            'industry_type': '行业类型（申万一级、申万二级等）',
            'source': '数据来源'
        }
        for field, comment in field_comments.items():
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.{} IS %s").format(
                sql.Identifier(TABLE_NAME),
                sql.Identifier(field)
            ), (comment,))

        conn.commit()
        print(f"Table {TABLE_NAME} initialized")
    except Exception as e:
        print(f"Table creation error: {e}")
        conn.rollback()

# 数据存在性检查
def has_industry_sw_data(conn, stock_code):
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("""
            SELECT EXISTS (
                SELECT 1 FROM {} 
                WHERE stock_code = %s
            )
        """).format(sql.Identifier(TABLE_NAME)), (stock_code,))
        return cur.fetchone()[0]
    except Exception as e:
        print(f"Existence check error: {e}")
        return False

# 批量插入/更新
def upsert_industry_sw(conn, stock_code, industry_data):
    try:
        cur = conn.cursor()
        
        # 准备数据
        data = [
            (stock_code, row['sw_code'], row['industry_name'], 
             row['industry_type'], row.get('source'))
            for _, row in industry_data.iterrows()
        ]
        
        # 执行批量操作
        extras.execute_values(
            cur,
            sql.SQL("""
                INSERT INTO {} (stock_code, sw_code, industry_name, industry_type, source)
                VALUES %s
                ON CONFLICT (stock_code, sw_code, industry_type) DO UPDATE
                SET industry_name = EXCLUDED.industry_name,
                    source = EXCLUDED.source
            """).format(sql.Identifier(TABLE_NAME)),
            data,
            page_size=100
        )
        
        conn.commit()
        print(f"Upserted {len(data)} rows for {stock_code}")
    except Exception as e:
        print(f"Upsert error: {e}")
        conn.rollback()

# 主函数
def main():
    conn = connect_to_db()
    if not conn:
        return

    try:
        # 初始化表
        create_industry_sw_table(conn)

        # 正式环境使用（取消注释）
        # 获取所有股票代码
        # stocks_df = adata.stock.info.all_code()
        
        # 测试数据（正式环境需注释）
        stocks_df = adata.stock.info.all_code().head(10)

        if stocks_df is None or stocks_df.empty:
            print("No stock codes found")
            return

        # 处理每个股票
        for stock_code in stocks_df['stock_code']:
            if has_industry_sw_data(conn, stock_code):
                print(f"Skipping existing data for {stock_code}")
                continue
                
            try:
                # 获取行业数据
                industry_df = adata.stock.info.get_industry_sw(stock_code=stock_code)
                if not industry_df.empty:
                    upsert_industry_sw(conn, stock_code, industry_df)
                else:
                    print(f"No data found for {stock_code}")
            except Exception as e:
                print(f"API error for {stock_code}: {e}")
                
    finally:
        conn.close()

if __name__ == "__main__":
    main()