import adata
import psycopg2
from psycopg2 import sql

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建股票所属板块信息表（如果不存在）并添加注释
def create_stock_plate_info_table(conn):
    table_name = 'ok_finance_stock_plate_info_east'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT NOT NULL,
                    plate_code TEXT NOT NULL,
                    plate_name TEXT NOT NULL,
                    plate_type TEXT NOT NULL,
                    source TEXT NOT NULL
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票所属板块信息';").format(sql.Identifier(table_name)))

            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.plate_code IS '板块代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.plate_name IS '板块名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.plate_type IS '板块类型';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '数据来源';").format(sql.Identifier(table_name)))

            conn.commit()
            print(f"Table {table_name} created successfully with comments!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入股票所属板块信息
def insert_stock_plate_info(conn, plate_data):
    try:
        cur = conn.cursor()
        for index, row in plate_data.iterrows():
            stock_code = row['stock_code']
            # 执行插入操作
            cur.execute(sql.SQL("""
                INSERT INTO ok_finance_stock_plate_info_east (stock_code, plate_code, plate_name, plate_type, source)
                VALUES (%s, %s, %s, %s, %s);
            """), (stock_code, row['plate_code'], row['plate_name'], row['plate_type'], row['source']))

        conn.commit()
        print("Inserted/Updated stock plate information successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取并存储单只股票所属板块信息
def fetch_and_store_stock_plate_info(conn, stock_code, clear_data):
    try:
        if not clear_data:
            # 检查表中是否已存在该股票代码
            cur = conn.cursor()
            cur.execute("SELECT EXISTS(SELECT 1 FROM ok_finance_stock_plate_info_east WHERE stock_code = %s);", (stock_code,))
            exists = cur.fetchone()[0]

            if exists:
                print(f"Stock code {stock_code} already exists in the database, skipping.")
                return

        df = adata.stock.info.get_plate_east(stock_code=stock_code)
        print(f"Fetched plate data for stock code {stock_code} successfully!")
        insert_stock_plate_info(conn, df)
    except Exception as e:
        print(f"Error fetching or inserting data for stock code {stock_code}: {e}")

# 获取所有股票代码并按需处理
def process_all_stock_codes(conn, clear_data):
    try:
        all_codes_df = adata.stock.info.all_code()
        for index, row in all_codes_df.iterrows():
            stock_code = row['stock_code']
            fetch_and_store_stock_plate_info(conn, stock_code, clear_data)
    except Exception as e:
        print(f"Error processing all stock codes: {e}")

# 主函数
def main(clear_data=True):
    conn = connect_to_db()
    if conn is None:
        return

    try:
        # 创建股票所属板块信息表
        create_stock_plate_info_table(conn)

        # 处理所有股票代码
        process_all_stock_codes(conn, clear_data)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main(clear_data=True)  # 设置为 True 或 False 控制是否清空数据