import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
from datetime import datetime
import os

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """
    检查表是否存在
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建股本信息表（如果不存在）并添加注释
def create_stock_shares_table(conn):
    """
    创建股本信息表（如果不存在）并添加注释
    """
    table_name = 'ok_finance_stock_shares'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT NOT NULL,
                    total_shares NUMERIC(20, 0),
                    limit_shares NUMERIC(20, 0),
                    list_a_shares NUMERIC(20, 0),
                    change_reason TEXT,
                    change_date DATE NOT NULL,
                    UNIQUE(stock_code, change_date)
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储所有股票的股本信息';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.total_shares IS '总股本';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.limit_shares IS '限售股本';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.list_a_shares IS 'A 股流通股本';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_reason IS '变更原因';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.change_date IS '变更日期';").format(sql.Identifier(table_name)))
            
            # 添加索引
            cur.execute(sql.SQL("CREATE INDEX idx_stock_shares_stock_code ON {} (stock_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_stock_shares_change_date ON {} (change_date);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_stock_shares_stock_code_change_date ON {} (stock_code, change_date);").format(sql.Identifier(table_name)))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 查询数据库中是否已存在该股票的数据
def has_stock_data(conn, stock_code):
    """
    查询数据库中是否已存在该股票的数据
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM ok_finance_stock_shares
                WHERE stock_code = %s
            );
        """, (stock_code,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if stock data exists: {e}")
        return False

# 插入或更新股本信息
def insert_or_update_stock_shares(conn, stock_code, shares_data):
    """
    插入或更新股本信息
    - 如果数据已存在，则更新数据。
    - 如果数据不存在，则插入新数据。
    """
    try:
        cur = conn.cursor()
        # 使用 execute_values 批量插入或更新
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_stock_shares (
                stock_code, total_shares, limit_shares, list_a_shares, change_reason, change_date
            )
            VALUES %s
            ON CONFLICT (stock_code, change_date) DO UPDATE
            SET
                total_shares = EXCLUDED.total_shares,
                limit_shares = EXCLUDED.limit_shares,
                list_a_shares = EXCLUDED.list_a_shares,
                change_reason = EXCLUDED.change_reason;
            """,
            [
                (stock_code, row['total_shares'], row['limit_shares'], row['list_a_shares'], row['change_reason'], row['change_date'])
                for index, row in shares_data.iterrows()
            ],
            template=None,
            page_size=100
        )
        conn.commit()
        print(f"Upserted {len(shares_data)} rows into ok_finance_stock_shares for stock {stock_code} successfully!")
    except Exception as e:
        print(f"Error upserting data: {e}")

# 获取股本信息
def fetch_stock_shares(stock_code, is_history=True):
    try:
        df = adata.stock.info.get_stock_shares(stock_code=stock_code, is_history=is_history)
        print(f"Fetched stock shares data for stock {stock_code} successfully!")
        return df
    except Exception as e:
        print(f"Error fetching stock shares data for stock {stock_code}: {e}")
        return None

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建股本信息表（如果不存在）并添加注释
        create_stock_shares_table(conn)

        # 获取所有股票代码
        stocks_df = adata.stock.info.all_code()

        # 创建一个包含固定股票代码的 DataFrame 用于测试
        # stocks_df = pd.DataFrame({
        #     'stock_code': ['600001', '600000']  # 示例股票代码
        # })
        if stocks_df is None:
            return
        
        # 遍历所有股票代码
        for index, row in stocks_df.iterrows():
            stock_code = row['stock_code']
            
            # 检查数据库中是否已存在该股票的数据
            # if has_stock_data(conn, stock_code):
            #     # 如果存在，则只获取最新数据
            #     shares_data = fetch_stock_shares(stock_code, is_history=False)
            # else:
            #     # 如果不存在，则获取所有历史数据
            #     shares_data = fetch_stock_shares(stock_code, is_history=True)
            if not has_stock_data(conn, stock_code):
                shares_data = fetch_stock_shares(stock_code, is_history=True)
                if shares_data is not None:
                    # 插入或更新股本信息
                    insert_or_update_stock_shares(conn, stock_code, shares_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()