import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
from datetime import datetime
import os
import numpy as np  # 导入numpy

# 概念指数信息-ths
# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """检查表是否存在"""
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建同花顺概念代码信息表（如果不存在）并添加注释
def create_concept_code_ths_table(conn):
    """创建同花顺概念代码信息表（如果不存在）并添加注释"""
    table_name = 'ok_finance_concept_code_ths'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    name TEXT NOT NULL,
                    index_code TEXT,
                    concept_code TEXT,  -- 允许 NULL
                    source TEXT
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储同花顺的概念代码信息';").format(sql.Identifier(table_name)))

            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.name IS '概念名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '同花顺的概念指数代码（8 开头）；例：885312';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.concept_code IS '同花顺的概念代码（可为 NULL）；例：309061';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '数据来源';").format(sql.Identifier(table_name)))

            # 添加索引
            cur.execute(sql.SQL("CREATE INDEX idx_concept_code_ths_index_code ON {} (index_code);").format(sql.Identifier(table_name)))

            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
            # 清空所有数据
            clear_table_data(conn, table_name)

    except Exception as e:
        print(f"Error creating table: {e}")

# 清空表数据
def clear_table_data(conn, table_name):
    """清空表数据"""
    try:
        cur = conn.cursor()
        cur.execute(sql.SQL("TRUNCATE TABLE {};").format(sql.Identifier(table_name)))
        conn.commit()
        print(f"All data in table {table_name} has been cleared.")
    except Exception as e:
        print(f"Error clearing table data: {e}")

# 插入同花顺概念代码信息并清理数据
def insert_concept_code_ths(conn, concept_data):
    """插入同花顺概念代码信息，并清理数据"""
    try:
        cur = conn.cursor()

        # 清理数据，将 NaN 替换为 None
        cleaned_data = []
        for index, row in concept_data.iterrows():
            cleaned_row = (
                row['name'],
                row['index_code'] if pd.notna(row['index_code']) else None,
                row['concept_code'] if pd.notna(row['concept_code']) else None,
                row['source'] if pd.notna(row['source']) else None
            )
            cleaned_data.append(cleaned_row)

        # 执行插入操作
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_concept_code_ths (
                name, index_code, concept_code, source
            )
            VALUES %s
            """,
            cleaned_data,
            template=None,
            page_size=100
        )
        conn.commit()
        print(f"Inserted {len(cleaned_data)} rows into ok_finance_concept_code_ths successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取同花顺概念代码信息
def fetch_concept_code_ths():
    """获取同花顺概念代码信息"""
    try:
        df = adata.stock.info.all_concept_code_ths()
        print("Fetched THS concept code data successfully!")
        return df
    except Exception as e:
        print(f"Error fetching THS concept code data: {e}")
        return None

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建同花顺概念代码信息表（如果不存在）并添加注释
        create_concept_code_ths_table(conn)

        # 获取同花顺概念代码信息
        concept_data = fetch_concept_code_ths()
        
        if concept_data is not None:
            # 插入同花顺概念代码信息
            insert_concept_code_ths(conn, concept_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()