import adata
import psycopg2
from psycopg2 import sql

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite_finance',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建A股指数信息表（如果不存在）并添加注释，创建索引
def create_index_info_table(conn):
    table_name = 'ok_finance_index_info'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    index_code TEXT NOT NULL UNIQUE,
                    concept_code TEXT NOT NULL,
                    name TEXT NOT NULL,
                    source TEXT NOT NULL
                );
            """).format(sql.Identifier(table_name)))

            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储A股指数信息';").format(sql.Identifier(table_name)))

            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '指数代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.concept_code IS '概念代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.name IS '指数名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '数据来源';").format(sql.Identifier(table_name)))

            # 创建索引以优化查询
            cur.execute(sql.SQL("CREATE INDEX idx_ok_finance_index_info_index_code ON {} (index_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_ok_finance_index_info_concept_code ON {} (concept_code);").format(sql.Identifier(table_name)))

            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入A股指数信息
def insert_index_info(conn, index_data):
    try:
        cur = conn.cursor()
        for index, row in index_data.iterrows():
            index_code = row['index_code']
            # 执行插入操作
            cur.execute(sql.SQL("""
                INSERT INTO ok_finance_index_info (index_code, concept_code, name, source)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (index_code) DO NOTHING;  -- 避免重复插入
            """), (index_code, row['concept_code'], row['name'], row['source']))

        conn.commit()
        print("Inserted/Updated index information successfully!")
    except Exception as e:
        print(f"Error inserting data: {e}")

# 获取并存储A股所有指数信息
def fetch_and_store_index_info(conn, clear_data):
    try:
        if clear_data:
            cur = conn.cursor()
            cur.execute("DELETE FROM ok_finance_index_info;")
            conn.commit()
            print("Existing index data cleared successfully!")

        df = adata.stock.info.all_index_code()
        print("Fetched index information successfully!")
        insert_index_info(conn, df)
    except Exception as e:
        print(f"Error fetching or inserting index information: {e}")

# 主函数
def main(clear_data=True):
    conn = connect_to_db()
    if conn is None:
        return

    try:
        # 创建A股指数信息表
        create_index_info_table(conn)

        # 获取并存储所有指数信息
        fetch_and_store_index_info(conn, clear_data)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main(clear_data=True)  # 设置为 True 或 False 控制是否清空数据