import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
from datetime import datetime
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite',  # 数据库名称
    'user': 'postgres',              # 数据库用户名
    'password': 'riusky2025',        # 数据库密码
    'host': 'localhost',             # 数据库主机
    'port': 5432                     # 数据库端口
}

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 检查表是否存在
def table_exists(conn, table_name):
    """
    检查表是否存在
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            );
        """, (table_name,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if table exists: {e}")
        return False

# 创建申万行业信息表（如果不存在）并添加注释
def create_industry_sw_table(conn):
    """
    创建申万行业信息表（如果不存在）并添加注释
    """
    table_name = 'ok_finance_industry_sw'
    try:
        if not table_exists(conn, table_name):
            cur = conn.cursor()
            cur.execute(sql.SQL("""
                CREATE TABLE {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                    stock_code TEXT NOT NULL,
                    sw_code TEXT NOT NULL,
                    industry_name TEXT NOT NULL,
                    industry_type TEXT NOT NULL,
                    source TEXT,
                    UNIQUE(stock_code, sw_code, industry_type)
                );
            """).format(sql.Identifier(table_name)))
            
            # 添加表注释
            cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储股票的申万行业分类信息';").format(sql.Identifier(table_name)))
            
            # 添加字段注释
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键，从 1000 开始';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.sw_code IS '申万行业代码';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.industry_name IS '行业名称';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.industry_type IS '行业类型（申万一级、申万二级等）';").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("COMMENT ON COLUMN {}.source IS '数据来源';").format(sql.Identifier(table_name)))
            
            # 添加索引
            cur.execute(sql.SQL("CREATE INDEX idx_industry_sw_stock_code ON {} (stock_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_industry_sw_sw_code ON {} (sw_code);").format(sql.Identifier(table_name)))
            cur.execute(sql.SQL("CREATE INDEX idx_industry_sw_industry_type ON {} (industry_type);").format(sql.Identifier(table_name)))
            
            conn.commit()
            print(f"Table {table_name} created successfully with comments and indexes!")
        else:
            print(f"Table {table_name} already exists.")
    except Exception as e:
        print(f"Error creating table: {e}")

# 查询数据库中是否已存在该股票的申万行业数据
def has_industry_sw_data(conn, stock_code):
    """
    查询数据库中是否已存在该股票的申万行业数据
    """
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM ok_finance_industry_sw
                WHERE stock_code = %s
            );
        """, (stock_code,))
        exists = cur.fetchone()[0]
        return exists
    except Exception as e:
        print(f"Error checking if industry SW data exists: {e}")
        return False

# 插入或更新申万行业信息
def insert_or_update_industry_sw(conn, stock_code, industry_data):
    """
    插入或更新申万行业信息
    - 如果数据已存在，则更新数据。
    - 如果数据不存在，则插入新数据。
    """
    try:
        cur = conn.cursor()
        # 使用 execute_values 批量插入或更新
        extras.execute_values(
            cur,
            """
            INSERT INTO ok_finance_industry_sw (
                stock_code, sw_code, industry_name, industry_type, source
            )
            VALUES %s
            ON CONFLICT (stock_code, sw_code, industry_type) DO UPDATE
            SET
                industry_name = EXCLUDED.industry_name,
                source = EXCLUDED.source;
            """,
            [
                (stock_code, row['sw_code'], row['industry_name'], row['industry_type'], row['source'])
                for index, row in industry_data.iterrows()
            ],
            template=None,
            page_size=100
        )
        conn.commit()
        print(f"Upserted {len(industry_data)} rows into ok_finance_industry_sw for stock {stock_code} successfully!")
    except Exception as e:
        print(f"Error upserting data: {e}")

# 获取申万行业信息
def fetch_industry_sw(stock_code):
    try:
        df = adata.stock.info.get_industry_sw(stock_code=stock_code)
        print(f"Fetched industry SW data for stock {stock_code} successfully!")
        return df
    except Exception as e:
        print(f"Error fetching industry SW data for stock {stock_code}: {e}")
        return None

# 主函数
def main():
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建申万行业信息表（如果不存在）并添加注释
        create_industry_sw_table(conn)

        # 获取所有股票代码
        stocks_df = adata.stock.info.all_code()

        # 创建一个包含固定股票代码的 DataFrame 用于测试
        # stocks_df = pd.DataFrame({
        #     'stock_code': ['300033', '600000']  # 示例股票代码
        # })
        if stocks_df is None:
            return
        
        # 遍历所有股票代码
        for index, row in stocks_df.iterrows():
            stock_code = row['stock_code']
            
            # 检查数据库中是否已经存在该股票的申万行业数据
            if has_industry_sw_data(conn, stock_code):
                print(f"Industry SW data for stock {stock_code} already exists. Skipping...")
                continue
            
            # 获取申万行业信息
            industry_data = fetch_industry_sw(stock_code)
            
            if industry_data is not None:
                # 插入或更新申万行业信息
                insert_or_update_industry_sw(conn, stock_code, industry_data)
    
    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    main()