import adata
import pandas as pd
import psycopg2
from psycopg2 import sql, extras
import time  # 用于控制请求间隔
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
# 概念指数成分信息-ths
# 数据库连接配置
DB_CONFIG = {
    'dbname': 'ocean_kite',
    'user': 'postgres',
    'password': 'riusky2025',
    'host': 'localhost',
    'port': 5432
}

TABLE_NAME = 'ok_finance_stock_concept_constituent_ths'
PREFIX = 'ok_finance_stock_'
# 索引名称生成器
def generate_index_name(column_name):
    """生成标准化索引名称：idx_<简化的表名>_<字段名>"""
    stripped_table = TABLE_NAME.replace(PREFIX, "", 1)  # 移除前缀
    return f"idx_{stripped_table}_{column_name}"

# 连接到 PostgreSQL 数据库
def connect_to_db():
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        print("Connected to the database successfully!")
        return conn
    except Exception as e:
        print(f"Error connecting to the database: {e}")
        return None

# 创建概念成分信息表（如果不存在）并添加注释
def create_concept_constituent_table(conn):
    """创建概念成分信息表（如果不存在）并添加注释"""
    try:
        cur = conn.cursor()
        
        # 建表语句
        cur.execute(sql.SQL("""
            CREATE TABLE IF NOT EXISTS {} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                index_code VARCHAR(64),
                stock_code VARCHAR(64),
                short_name VARCHAR(64),
                UNIQUE(stock_code, index_code)
            );
        """).format(sql.Identifier(TABLE_NAME)))

        # 动态创建索引
        indexes = [
            ("index_code", "index_code"),
            ("stock_code", "stock_code"),
            ("composite", "stock_code, index_code")  # 复合索引
        ]
        
        for idx_type, columns in indexes:
            idx_name = generate_index_name(idx_type)
            cur.execute(sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} ({})").format(
                sql.Identifier(idx_name),
                sql.Identifier(TABLE_NAME),
                sql.SQL(columns)
            ))

        # 添加表注释
        cur.execute(sql.SQL("COMMENT ON TABLE {} IS '存储概念成分信息';").format(sql.Identifier(TABLE_NAME)))

        # 添加字段注释
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.id IS '自增主键';").format(sql.Identifier(TABLE_NAME)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.index_code IS '概念指数代码';").format(sql.Identifier(TABLE_NAME)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.stock_code IS '股票代码';").format(sql.Identifier(TABLE_NAME)))
        cur.execute(sql.SQL("COMMENT ON COLUMN {}.short_name IS '股票名称';").format(sql.Identifier(TABLE_NAME)))

        conn.commit()
        print(f"Table {TABLE_NAME} created successfully with comments!")
    except Exception as e:
        print(f"Error creating table: {e}")

# 插入概念成分信息
def insert_concept_constituent(conn, constituents):
    """使用动态表名插入数据"""
    try:
        cur = conn.cursor()
        extras.execute_values(
            cur,
            sql.SQL("""
                INSERT INTO {} (index_code, stock_code, short_name)
                VALUES %s
                ON CONFLICT (stock_code, index_code) DO NOTHING
            """).format(sql.Identifier(TABLE_NAME)),
            constituents,
            page_size=100
        )
        conn.commit()
        print(f"Inserted {len(constituents)} rows successfully!")
    except Exception as e:
        print(f"Insert error: {e}")

# 检查是否存在某个 index_code 或 concept_code
def check_exist(conn, code, code_type='index'):
    """动态表名的存在性检查"""
    try:
        cur = conn.cursor()
        if code_type == 'index':
            query = sql.SQL("SELECT EXISTS(SELECT 1 FROM {} WHERE index_code = %s)").format(sql.Identifier(TABLE_NAME))
        else:
            query = sql.SQL("SELECT EXISTS(SELECT 1 FROM {} WHERE stock_code = %s)").format(sql.Identifier(TABLE_NAME))
            
        cur.execute(query, (code,))
        return cur.fetchone()[0]
    except Exception as e:
        print(f"Existence check error: {e}")
        return False

# 获取概念成分信息
def fetch_and_store_constituents(conn, concept_data, wait_time=0):
    """获取并存储概念成分信息"""
    constituents_data = []

    for _, row in concept_data.iterrows():
        index_code = row['index_code']
        concept_code = row['concept_code']
        
        if pd.isna(index_code) or index_code == "":
            print(f"Index code for concept '{row['name']}' is invalid or empty, checking concept_code...")
            index_code = None  # 将 index_code 置为 None，以便只查询 concept_code
        
        # 尝试根据 index_code 获取成分信息
        if index_code and not check_exist(conn, index_code):
            try:
                constituents = adata.stock.info.concept_constituent_ths(index_code=index_code, wait_time=wait_time)
                if not constituents.empty:
                    for _, constituent in constituents.iterrows():
                        constituents_data.append((index_code, constituent['stock_code'], constituent['short_name']))
                    print(f"Fetched constituents for index code {index_code} successfully!")
                    continue  # 如果找到index_code的成分，直接跳过到下一个概念
            except Exception as e:
                print(f"Error fetching constituency for index code {index_code}: {e}")
        
        # 如果没有找到 constituents, 根据 concept_code 获取成分信息
        if concept_code and not check_exist(conn, concept_code):
            try:
                constituents = adata.stock.info.concept_constituent_ths(concept_code=concept_code, wait_time=wait_time)
                if not constituents.empty:
                    for _, constituent in constituents.iterrows():
                        constituents_data.append((None, constituent['stock_code'], constituent['short_name']))  # 保存为 None 的 index_code
                    print(f"Fetched constituents for concept code {concept_code} successfully!")
            except Exception as e:
                print(f"Error fetching constituency for concept code {concept_code}: {e}")

    # 把收集到的成分数据插入数据库
    if constituents_data:
        insert_concept_constituent(conn, constituents_data)

# 主函数
def main(wait_time=0):
    # 连接到数据库
    conn = connect_to_db()
    if conn is None:
        return
    
    try:
        # 创建概念成分信息表
        create_concept_constituent_table(conn)

        # 获取所有概念信息
        # concept_data = adata.stock.info.all_concept_code_ths()
        # 取前10条数据作为测试数据
        concept_data = adata.stock.info.all_concept_code_ths().head(10)
        print("Fetched all concept code data successfully!")

        # 获取并存储各概念的成分信息
        fetch_and_store_constituents(conn, concept_data, wait_time=wait_time)

    finally:
        # 关闭数据库连接
        conn.close()

if __name__ == "__main__":
    # 控制请求间隔时间
    main(wait_time=1000)  # 例如：等待 1000 毫秒（1秒）